version: '3'
services:
  trump-postgis:
    image: slothofanarchy/trump-postgis
    build: ./postgis/
    env_file:
      - ./postgis/env
    volumes:
      - data:/var/lib/postgresql/data
    restart: on-failure
  trump-mapnik:
    image: slothofanarchy/trump-mapnik
    build: ./mapnik/
    links:
      - trump-postgis
    tty: true
    volumes:
      - cache:/var/lib/mod_tile
    restart: on-failure
  trump-area:
    image: slothofanarchy/trump-area
    build: ./area/
    links:
      - trump-postgis
    tty: true
    restart: on-failure
  trump-label:
    image: slothofanarchy/trump-label
    build: ./label/
    tty: true
    restart: on-failure
  trump-client:
    image: slothofanarchy/trump-client
    build: ./client/
    tty: true
    restart: on-failure
    depends_on:
      - trump-mapnik
      - trump-area
      - trump-label
    ports:
      - 80:80
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --cleanup
volumes:
  data: {} # postgis data
  cache: {} # mapnik tile cache
