version: '3'
services:
  trump-postgis:
    image: mdillon/postgis:11
    env_file:
      - ./postgis/env
    volumes:
      - data:/var/lib/postgresql/data
    restart: on-failure
  trump-mapnik:
    image: slothofanarchy/trump-mapnik
    build: ./mapnik/
    env_file:
      - ./mapnik/env
    links:
      - trump-postgis
    tty: true
    volumes:
      - cache:/var/lib/mod_tile
    restart: on-failure
  trump-area:
    image: slothofanarchy/trump-area
    build: ./area/
    env_file:
      - ./area/env
    links:
      - trump-postgis
    tty: true
    restart: on-failure
  trump-label:
    image: slothofanarchy/trump-label
    build: ./label/
    env_file:
      - ./postgis/env
    tty: true
    volumes:
      - labels:/home/osm/labels
    restart: on-failure
  trump-client:
    image: slothofanarchy/trump-client
    build: ./client/
    tty: true
    restart: on-failure
    env_file:
      - ./client/env
    depends_on:
      - trump-mapnik
      - trump-area
      - trump-label
    ports:
      - 80:80
volumes:
  data: {} # postgis data
  cache: {} # mapnik tile cache
  labels: {} # dir for label ce file
